development:
  adapter: anycable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: streaming_logs_dev

test:
  adapter: async

production:
  adapter: anycable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: streaming_logs_production

