update_daily_leaderboards:
  cron: "*/45 * * * * *"
  class: "UpdateLeaderboardsJob"
  queue: default
  args: "daily"

update_weekly_leaderboards:
  cron: "*/5 * * * *"
  class: "UpdateLeaderboardsJob"
  queue: default
  args: "weekly"

update_monthly_leaderboards:
  cron: "*/10 * * * *"
  class: "UpdateLeaderboardsJob"
  queue: default
  args: "monthly"

delete_old_achievements:
  cron: "0 1 * * *"
  class: "DeleteOldAchievementsJob"

subtract_expired_achievements:
  cron: "*/5 * * * *"
  class: "ExpireAchievementsJob"
  queue: default
